//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte Id_FarmGroup { get; set; }
        public byte Id_ReleaseForm { get; set; }
    
        public virtual FarmGroup FarmGroup { get; set; }
        public virtual ReleaseForm ReleaseForm { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
