//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int Id_Medicine { get; set; }
        public int Id_Client { get; set; }
        public byte Amount { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
